### ISSUE TITLE
homepage in gemspec is incorrect

### ISSUE THREAD

**Issue by viktorbenei** [rikas/iosdevices#1]
The homepage property in .gemspec points to ios**-**devices instead of **iosdevices**. Clicking on the Homepage link on Rubygems shows GitHub's 404 page.

Either that should be corrected or the repository should be moved.

**Comment by rikas** [comment]
Thank you @viktorbenei, I will fix this right away.

**Comment by rikas** [comment]
It's fixed on version 0.2.1.
